// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eafinoxllrjqskyvcxrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZmlub3hsbHJqcXNreXZjeHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDczODMsImV4cCI6MjA3MjYyMzM4M30.0lXlai4_uNH9yFmiBz_MUVbgyV4MZq64WNkQWeNOCWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});